### ISSUE TITLE
Fatal error after Updating to latest Autoprefixer

### ISSUE THREAD

**Issue by ozone1979** [vladkens/autoprefixer-php#17]
I get this error after updating then running the suggested short test ('a { transition: transform 1s }').

Fatal error: Uncaught AutoprefixerException: In css[0]: autoprefixer(...).process is not a function in C:\wamp64\www\_modules\PHP\CSS\Autoprefixer\test\vendor\vladkens\autoprefixer\lib\Autoprefixer.php:81 Stack trace: #0 C:\wamp64\www\_modules\PHP\CSS\Autoprefixer\test\index.php(8): Autoprefixer->compile(Array) #1 {main} thrown in C:\wamp64\www\_modules\PHP\CSS\Autoprefixer\test\vendor\vladkens\autoprefixer\lib\Autoprefixer.php on line 81

**Comment by Yonn-Trimoreau** [comment]
My PR should fix this issue

**Comment by Yonn-Trimoreau** [comment]
You can use my repo as a composer vcs repo if you need it before it is merged (since this repo appears to be dead..)

**Comment by vladkens** [comment]
Merged
